os: linux
language: shell
install: skip

before_deploy:
  - if [[ $TRAVIS_TEST_RESULT == 1 ]]; then echo "exiting due to failed build"; sleep 2; exit 1; fi
deploy:
  provider: s3
  script: ./deploy.sh
  on:
    branch: master
  edge: true

jobs:
  include:
    - name: PASSING
      script:
        - sleep 2
    - name: FAILING
      script:
        - false
